/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MainUI from "./script/MainUI"
import Test_9_TimeLineUI from "./study/Test_9_TimeLineUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedheight";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/MainUI.ts",MainUI);
        reg("study/Test_9_TimeLineUI.ts",Test_9_TimeLineUI);
    }
}
GameConfig.init();