/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class MainUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Main");
        }
    }
    REG("ui.MainUI",MainUI);
    export class TestUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Test");
        }
    }
    REG("ui.TestUI",TestUI);
    export class Test1UI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Test1");
        }
    }
    REG("ui.Test1UI",Test1UI);
    export class TimeLineUI extends Dialog {
		public bear:Laya.Animation;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("TimeLine");
        }
    }
    REG("ui.TimeLineUI",TimeLineUI);
}
export module ui.UI_Loading {
    export class UI_LoadingUI extends View {
		public ani1:Laya.FrameAnimation;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("UI_Loading/UI_Loading");
        }
    }
    REG("ui.UI_Loading.UI_LoadingUI",UI_LoadingUI);
}