/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package game.ui.UI_Loading {
	import laya.ui.*;import laya.display.*; 

	public class UI_LoadingUI extends View {
		public var ani1:FrameAnimation;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":640,"height":1136},"compId":2,"child":[{"type":"Sprite","props":{"y":568,"x":320,"width":54,"texture":"UI_Loading/loading.png","pivotY":27,"pivotX":27,"height":54},"compId":9}],"animations":[{"nodes":[{"target":9,"keyframes":{"x":[{"value":320,"tweenMethod":"linearNone","tween":true,"target":9,"key":"x","index":0},{"value":320,"tweenMethod":"linearNone","tween":true,"target":9,"key":"x","index":30}],"rotation":[{"value":0,"tweenMethod":"linearNone","tween":true,"target":9,"key":"rotation","index":0},{"value":360,"tweenMethod":"linearNone","tween":true,"target":9,"key":"rotation","index":30}],"name":[{"value":"","tweenMethod":"linearNone","tween":false,"target":9,"key":"name","index":0},{"value":"loadingAni","tweenMethod":"linearNone","tween":false,"target":9,"key":"name","index":30}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["UI_Loading/loading.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}