/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module game.ui {
    export class MainUI extends View {
        public static  uiView:any ={"type":"View","props":{"width":640,"runtime":"script/MainUI.ts","name":"MainUI","height":1136},"compId":2,"child":[{"type":"Sprite","props":{"zOrder":0,"y":318.5,"x":82,"width":476,"texture":"Fruits/8.png","height":518},"compId":3},{"type":"Panel","props":{"y":374,"x":69,"width":195,"visible":true,"vScrollBarSkin":"comp/vscroll.png","height":407},"compId":10,"child":[{"type":"Sprite","props":{"zOrder":10,"y":165,"x":29,"width":108,"texture":"Fruits/eat4.png","height":108},"compId":11},{"type":"Sprite","props":{"y":27,"x":35,"width":96,"texture":"Fruits/eat3.png","height":113},"compId":12},{"type":"Sprite","props":{"y":281,"x":17.5,"width":143,"texture":"Fruits/8.png","height":199},"compId":13}]}],"loadList":["Fruits/8.png","comp/vscroll.png","Fruits/eat4.png","Fruits/eat3.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(MainUI.uiView);
        }
    }
    REG("game.ui.MainUI",MainUI);
    export class TestUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Test");
        }
    }
    REG("game.ui.TestUI",TestUI);
    export class Test1UI extends View {
        public static  uiView:any ={"type":"View","props":{"width":640,"name":"Test1","height":1136},"compId":2,"child":[{"type":"Sprite","props":{"y":231,"x":0,"texture":"Fruits/5.png"},"compId":3,"child":[{"type":"Sprite","props":{"y":0,"x":288,"texture":"Fruits/8.png"},"compId":4}]}],"loadList":["Fruits/5.png","Fruits/8.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(Test1UI.uiView);
        }
    }
    REG("game.ui.Test1UI",Test1UI);
    export class TimeLineUI extends Dialog {
		public bear:Laya.Animation;
        public static  uiView:any ={"type":"Dialog","props":{"width":640,"runtime":"study/Test_9_TimeLineUI.ts","height":1136},"compId":2,"child":[{"type":"Animation","props":{"y":427,"x":290,"width":0,"var":"bear","source":"test/TimeLine.ani","rotation":0,"height":0},"compId":3}],"loadList":["test/TimeLine.ani"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(TimeLineUI.uiView);
        }
    }
    REG("game.ui.TimeLineUI",TimeLineUI);
}
export module game.ui.UI_Loading {
    export class UI_LoadingUI extends View {
		public ani1:Laya.FrameAnimation;
        public static  uiView:any ={"type":"View","props":{"width":640,"height":1136},"compId":2,"child":[{"type":"Sprite","props":{"y":568,"x":320,"width":54,"texture":"UI_Loading/loading.png","pivotY":27,"pivotX":27,"height":54},"compId":9}],"animations":[{"nodes":[{"target":9,"keyframes":{"x":[{"value":320,"tweenMethod":"linearNone","tween":true,"target":9,"key":"x","index":0},{"value":320,"tweenMethod":"linearNone","tween":true,"target":9,"key":"x","index":30}],"rotation":[{"value":0,"tweenMethod":"linearNone","tween":true,"target":9,"key":"rotation","index":0},{"value":360,"tweenMethod":"linearNone","tween":true,"target":9,"key":"rotation","index":30}],"name":[{"value":"","tweenMethod":"linearNone","tween":false,"target":9,"key":"name","index":0},{"value":"loadingAni","tweenMethod":"linearNone","tween":false,"target":9,"key":"name","index":30}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["UI_Loading/loading.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(UI_LoadingUI.uiView);
        }
    }
    REG("game.ui.UI_Loading.UI_LoadingUI",UI_LoadingUI);
}