/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package game.ui {
	import laya.ui.*;import laya.display.*; 
	import script/MainUI.ts;

	public class MainUI extends View {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":640,"runtime":"script/MainUI.ts","name":"MainUI","height":1136},"compId":2,"child":[{"type":"Sprite","props":{"zOrder":0,"y":318.5,"x":82,"width":476,"texture":"Fruits/8.png","height":518},"compId":3},{"type":"Panel","props":{"y":374,"x":69,"width":195,"visible":true,"vScrollBarSkin":"comp/vscroll.png","height":407},"compId":10,"child":[{"type":"Sprite","props":{"zOrder":10,"y":165,"x":29,"width":108,"texture":"Fruits/eat4.png","height":108},"compId":11},{"type":"Sprite","props":{"y":27,"x":35,"width":96,"texture":"Fruits/eat3.png","height":113},"compId":12},{"type":"Sprite","props":{"y":281,"x":17.5,"width":143,"texture":"Fruits/8.png","height":199},"compId":13}]}],"loadList":["Fruits/8.png","comp/vscroll.png","Fruits/eat4.png","Fruits/eat3.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}