/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package game.ui {
	import laya.ui.*;import laya.display.*; 

	public class TestUI extends View {

		override protected function createChildren():void {
			super.createChildren();
			loadScene("Test");

		}

	}
}