/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package game.ui {
	import laya.ui.*;import laya.display.*; 
	import study/Test_9_TimeLineUI.ts;

	public class TimeLineUI extends Dialog {
		public var bear:Animation;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Dialog","props":{"width":640,"runtime":"study/Test_9_TimeLineUI.ts","height":1136},"compId":2,"child":[{"type":"Animation","props":{"y":427,"x":290,"width":0,"var":"bear","source":"test/TimeLine.ani","rotation":0,"height":0},"compId":3}],"loadList":["test/TimeLine.ani"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}